name: Build and Publish GitHub Container Docker Image

on:
  release:
    types:
      - published
      - edited
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build_and_publish_docker_image:
    runs-on: ubuntu-latest
    steps:

      - name: Debug Variables
        run: |
          echo "github.actor: ${{ github.actor }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event.release.tag_name: ${{ github.event.release.tag_name }}"
          echo "github.event.repository.default_branch: ${{ github.event.repository.default_branch }}"
          echo "github.event.release.target_commitish: ${{ github.event.release.target_commitish }}"
          echo "github.event.release.prerelease: ${{ github.event.release.prerelease }}"
          echo "github.event.release.draft: ${{ github.event.release.draft }}"

      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Update Version in const.py
        if: ${{ github.event_name == 'release' && github.event.repository.default_branch == github.event.release.target_commitish && github.event.release.prerelease == false && github.event.release.draft == false }}
        run: |
          sed -i 's/VERSION \= \".*\"/VERSION \= \"${{ github.event.release.tag_name }}\"/' ./app/const.py

      - name: Commit & Push Version Changes
        if: ${{ github.event_name == 'release' && github.event.repository.default_branch == github.event.release.target_commitish && github.event.release.prerelease == false && github.event.release.draft == false }}
        uses: stefanzweifel/git-auto-commit-action@v5  # Current issues with v6 (9/15/25)
        with:
          commit_message: 'Updating to version ${{ github.event.release.tag_name }} [skip ci]'
          branch: ${{ github.event.repository.default_branch }}

      - name: Update Release with Version Changes Commit
        if: ${{ github.event_name == 'release' && github.event.repository.default_branch == github.event.release.target_commitish && github.event.release.prerelease == false && github.event.release.draft == false }}
        run: |
          git tag -f ${{ github.event.release.tag_name }}
          git push -f origin ${{ github.event.release.tag_name }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}},priority=1000
            type=ref,event=branch,enable={{is_not_default_branch}},priority=900
            type=edge,enable={{is_default_branch}},priority=800

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Container
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
